name: Deploy to S3 Buckets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --recursive --region us-east-1 build s3://${confess-bucket}
# Web Container Build/Test
## Get Source
## Build/Test
## Docker Image Build
## Login AWS
## Push image to ECR

# API Container Build/Test
## Get Source
## Build/Test
## Docker Image Build
## Login AWS
## Push image to ECR

# Deploy
## Get Source
## Login AWS
## Edit Task Definition
## Deploy
